// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: calculator.proto
// Protobuf C++ Version: 5.27.1

#include "calculator.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace calculator {

inline constexpr SubResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : difference_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SubResponse::SubResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SubResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SubResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SubResponseDefaultTypeInternal() {}
  union {
    SubResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SubResponseDefaultTypeInternal _SubResponse_default_instance_;

inline constexpr SubRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : minuend_{0},
        subtrahend_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SubRequest::SubRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SubRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SubRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SubRequestDefaultTypeInternal() {}
  union {
    SubRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SubRequestDefaultTypeInternal _SubRequest_default_instance_;

inline constexpr MulResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : product_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MulResponse::MulResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MulResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MulResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MulResponseDefaultTypeInternal() {}
  union {
    MulResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MulResponseDefaultTypeInternal _MulResponse_default_instance_;

inline constexpr MulRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : multiplicand_{0},
        multiplier_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MulRequest::MulRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MulRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MulRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MulRequestDefaultTypeInternal() {}
  union {
    MulRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MulRequestDefaultTypeInternal _MulRequest_default_instance_;

inline constexpr ModResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : result_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ModResponse::ModResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ModResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ModResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ModResponseDefaultTypeInternal() {}
  union {
    ModResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ModResponseDefaultTypeInternal _ModResponse_default_instance_;

inline constexpr ModRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : dividend_{0},
        divisor_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ModRequest::ModRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ModRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ModRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ModRequestDefaultTypeInternal() {}
  union {
    ModRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ModRequestDefaultTypeInternal _ModRequest_default_instance_;

inline constexpr DivResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : quotient_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DivResponse::DivResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DivResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DivResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DivResponseDefaultTypeInternal() {}
  union {
    DivResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DivResponseDefaultTypeInternal _DivResponse_default_instance_;

inline constexpr DivRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : dividend_{0},
        divisor_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR DivRequest::DivRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct DivRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR DivRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~DivRequestDefaultTypeInternal() {}
  union {
    DivRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 DivRequestDefaultTypeInternal _DivRequest_default_instance_;

inline constexpr AddResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : sum_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AddResponse::AddResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AddResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddResponseDefaultTypeInternal() {}
  union {
    AddResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddResponseDefaultTypeInternal _AddResponse_default_instance_;

inline constexpr AddRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : addend_1_{0},
        addend_2_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AddRequest::AddRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct AddRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddRequestDefaultTypeInternal() {}
  union {
    AddRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddRequestDefaultTypeInternal _AddRequest_default_instance_;
}  // namespace calculator
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_calculator_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_calculator_2eproto = nullptr;
const ::uint32_t
    TableStruct_calculator_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::calculator::AddRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::calculator::AddRequest, _impl_.addend_1_),
        PROTOBUF_FIELD_OFFSET(::calculator::AddRequest, _impl_.addend_2_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::calculator::AddResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::calculator::AddResponse, _impl_.sum_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::calculator::SubRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::calculator::SubRequest, _impl_.minuend_),
        PROTOBUF_FIELD_OFFSET(::calculator::SubRequest, _impl_.subtrahend_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::calculator::SubResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::calculator::SubResponse, _impl_.difference_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::calculator::MulRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::calculator::MulRequest, _impl_.multiplicand_),
        PROTOBUF_FIELD_OFFSET(::calculator::MulRequest, _impl_.multiplier_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::calculator::MulResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::calculator::MulResponse, _impl_.product_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::calculator::DivRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::calculator::DivRequest, _impl_.dividend_),
        PROTOBUF_FIELD_OFFSET(::calculator::DivRequest, _impl_.divisor_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::calculator::DivResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::calculator::DivResponse, _impl_.quotient_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::calculator::ModRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::calculator::ModRequest, _impl_.dividend_),
        PROTOBUF_FIELD_OFFSET(::calculator::ModRequest, _impl_.divisor_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::calculator::ModResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::calculator::ModResponse, _impl_.result_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::calculator::AddRequest)},
        {10, -1, -1, sizeof(::calculator::AddResponse)},
        {19, -1, -1, sizeof(::calculator::SubRequest)},
        {29, -1, -1, sizeof(::calculator::SubResponse)},
        {38, -1, -1, sizeof(::calculator::MulRequest)},
        {48, -1, -1, sizeof(::calculator::MulResponse)},
        {57, -1, -1, sizeof(::calculator::DivRequest)},
        {67, -1, -1, sizeof(::calculator::DivResponse)},
        {76, -1, -1, sizeof(::calculator::ModRequest)},
        {86, -1, -1, sizeof(::calculator::ModResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::calculator::_AddRequest_default_instance_._instance,
    &::calculator::_AddResponse_default_instance_._instance,
    &::calculator::_SubRequest_default_instance_._instance,
    &::calculator::_SubResponse_default_instance_._instance,
    &::calculator::_MulRequest_default_instance_._instance,
    &::calculator::_MulResponse_default_instance_._instance,
    &::calculator::_DivRequest_default_instance_._instance,
    &::calculator::_DivResponse_default_instance_._instance,
    &::calculator::_ModRequest_default_instance_._instance,
    &::calculator::_ModResponse_default_instance_._instance,
};
const char descriptor_table_protodef_calculator_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\020calculator.proto\022\ncalculator\"0\n\nAddReq"
    "uest\022\020\n\010addend_1\030\001 \001(\005\022\020\n\010addend_2\030\002 \001(\005"
    "\"\032\n\013AddResponse\022\013\n\003sum\030\001 \001(\003\"1\n\nSubReque"
    "st\022\017\n\007minuend\030\001 \001(\005\022\022\n\nsubtrahend\030\002 \001(\005\""
    "!\n\013SubResponse\022\022\n\ndifference\030\001 \001(\003\"6\n\nMu"
    "lRequest\022\024\n\014multiplicand\030\001 \001(\005\022\022\n\nmultip"
    "lier\030\002 \001(\005\"\036\n\013MulResponse\022\017\n\007product\030\001 \001"
    "(\003\"/\n\nDivRequest\022\020\n\010dividend\030\001 \001(\005\022\017\n\007di"
    "visor\030\002 \001(\005\"\037\n\013DivResponse\022\020\n\010quotient\030\001"
    " \001(\003\"/\n\nModRequest\022\020\n\010dividend\030\001 \001(\005\022\017\n\007"
    "divisor\030\002 \001(\005\"\035\n\013ModResponse\022\016\n\006result\030\001"
    " \001(\0032\256\002\n\nCalculator\0228\n\003Add\022\026.calculator."
    "AddRequest\032\027.calculator.AddResponse\"\000\0228\n"
    "\003Sub\022\026.calculator.SubRequest\032\027.calculato"
    "r.SubResponse\"\000\0228\n\003Mul\022\026.calculator.MulR"
    "equest\032\027.calculator.MulResponse\"\000\0228\n\003Div"
    "\022\026.calculator.DivRequest\032\027.calculator.Di"
    "vResponse\"\000\0228\n\003Mod\022\026.calculator.ModReque"
    "st\032\027.calculator.ModResponse\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_calculator_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_calculator_2eproto = {
    false,
    false,
    757,
    descriptor_table_protodef_calculator_2eproto,
    "calculator.proto",
    &descriptor_table_calculator_2eproto_once,
    nullptr,
    0,
    10,
    schemas,
    file_default_instances,
    TableStruct_calculator_2eproto::offsets,
    file_level_enum_descriptors_calculator_2eproto,
    file_level_service_descriptors_calculator_2eproto,
};
namespace calculator {
// ===================================================================

class AddRequest::_Internal {
 public:
};

AddRequest::AddRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:calculator.AddRequest)
}
AddRequest::AddRequest(
    ::google::protobuf::Arena* arena, const AddRequest& from)
    : AddRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE AddRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void AddRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, addend_1_),
           0,
           offsetof(Impl_, addend_2_) -
               offsetof(Impl_, addend_1_) +
               sizeof(Impl_::addend_2_));
}
AddRequest::~AddRequest() {
  // @@protoc_insertion_point(destructor:calculator.AddRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AddRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AddRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(AddRequest, _impl_._cached_size_),
              false,
          },
          &AddRequest::MergeImpl,
          &AddRequest::kDescriptorMethods,
          &descriptor_table_calculator_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> AddRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AddRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::calculator::AddRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 addend_2 = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AddRequest, _impl_.addend_2_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(AddRequest, _impl_.addend_2_)}},
    // int32 addend_1 = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AddRequest, _impl_.addend_1_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(AddRequest, _impl_.addend_1_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 addend_1 = 1;
    {PROTOBUF_FIELD_OFFSET(AddRequest, _impl_.addend_1_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 addend_2 = 2;
    {PROTOBUF_FIELD_OFFSET(AddRequest, _impl_.addend_2_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void AddRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:calculator.AddRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.addend_1_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.addend_2_) -
      reinterpret_cast<char*>(&_impl_.addend_1_)) + sizeof(_impl_.addend_2_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* AddRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:calculator.AddRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 addend_1 = 1;
  if (this->_internal_addend_1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_addend_1(), target);
  }

  // int32 addend_2 = 2;
  if (this->_internal_addend_2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_addend_2(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calculator.AddRequest)
  return target;
}

::size_t AddRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:calculator.AddRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // int32 addend_1 = 1;
  if (this->_internal_addend_1() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_addend_1());
  }

  // int32 addend_2 = 2;
  if (this->_internal_addend_2() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_addend_2());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AddRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AddRequest*>(&to_msg);
  auto& from = static_cast<const AddRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calculator.AddRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_addend_1() != 0) {
    _this->_impl_.addend_1_ = from._impl_.addend_1_;
  }
  if (from._internal_addend_2() != 0) {
    _this->_impl_.addend_2_ = from._impl_.addend_2_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AddRequest::CopyFrom(const AddRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calculator.AddRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AddRequest::InternalSwap(AddRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AddRequest, _impl_.addend_2_)
      + sizeof(AddRequest::_impl_.addend_2_)
      - PROTOBUF_FIELD_OFFSET(AddRequest, _impl_.addend_1_)>(
          reinterpret_cast<char*>(&_impl_.addend_1_),
          reinterpret_cast<char*>(&other->_impl_.addend_1_));
}

::google::protobuf::Metadata AddRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AddResponse::_Internal {
 public:
};

AddResponse::AddResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:calculator.AddResponse)
}
AddResponse::AddResponse(
    ::google::protobuf::Arena* arena, const AddResponse& from)
    : AddResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE AddResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void AddResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.sum_ = {};
}
AddResponse::~AddResponse() {
  // @@protoc_insertion_point(destructor:calculator.AddResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AddResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
AddResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(AddResponse, _impl_._cached_size_),
              false,
          },
          &AddResponse::MergeImpl,
          &AddResponse::kDescriptorMethods,
          &descriptor_table_calculator_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> AddResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_AddResponse_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::calculator::AddResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 sum = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(AddResponse, _impl_.sum_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(AddResponse, _impl_.sum_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 sum = 1;
    {PROTOBUF_FIELD_OFFSET(AddResponse, _impl_.sum_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void AddResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:calculator.AddResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.sum_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* AddResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:calculator.AddResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 sum = 1;
  if (this->_internal_sum() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_sum(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calculator.AddResponse)
  return target;
}

::size_t AddResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:calculator.AddResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 sum = 1;
  if (this->_internal_sum() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_sum());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void AddResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AddResponse*>(&to_msg);
  auto& from = static_cast<const AddResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calculator.AddResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_sum() != 0) {
    _this->_impl_.sum_ = from._impl_.sum_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AddResponse::CopyFrom(const AddResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calculator.AddResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AddResponse::InternalSwap(AddResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.sum_, other->_impl_.sum_);
}

::google::protobuf::Metadata AddResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SubRequest::_Internal {
 public:
};

SubRequest::SubRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:calculator.SubRequest)
}
SubRequest::SubRequest(
    ::google::protobuf::Arena* arena, const SubRequest& from)
    : SubRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SubRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SubRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, minuend_),
           0,
           offsetof(Impl_, subtrahend_) -
               offsetof(Impl_, minuend_) +
               sizeof(Impl_::subtrahend_));
}
SubRequest::~SubRequest() {
  // @@protoc_insertion_point(destructor:calculator.SubRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SubRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
SubRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(SubRequest, _impl_._cached_size_),
              false,
          },
          &SubRequest::MergeImpl,
          &SubRequest::kDescriptorMethods,
          &descriptor_table_calculator_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> SubRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SubRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::calculator::SubRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 subtrahend = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SubRequest, _impl_.subtrahend_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(SubRequest, _impl_.subtrahend_)}},
    // int32 minuend = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(SubRequest, _impl_.minuend_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SubRequest, _impl_.minuend_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 minuend = 1;
    {PROTOBUF_FIELD_OFFSET(SubRequest, _impl_.minuend_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 subtrahend = 2;
    {PROTOBUF_FIELD_OFFSET(SubRequest, _impl_.subtrahend_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void SubRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:calculator.SubRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.minuend_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.subtrahend_) -
      reinterpret_cast<char*>(&_impl_.minuend_)) + sizeof(_impl_.subtrahend_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* SubRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:calculator.SubRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 minuend = 1;
  if (this->_internal_minuend() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_minuend(), target);
  }

  // int32 subtrahend = 2;
  if (this->_internal_subtrahend() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_subtrahend(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calculator.SubRequest)
  return target;
}

::size_t SubRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:calculator.SubRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // int32 minuend = 1;
  if (this->_internal_minuend() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_minuend());
  }

  // int32 subtrahend = 2;
  if (this->_internal_subtrahend() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_subtrahend());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void SubRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SubRequest*>(&to_msg);
  auto& from = static_cast<const SubRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calculator.SubRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_minuend() != 0) {
    _this->_impl_.minuend_ = from._impl_.minuend_;
  }
  if (from._internal_subtrahend() != 0) {
    _this->_impl_.subtrahend_ = from._impl_.subtrahend_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SubRequest::CopyFrom(const SubRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calculator.SubRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SubRequest::InternalSwap(SubRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SubRequest, _impl_.subtrahend_)
      + sizeof(SubRequest::_impl_.subtrahend_)
      - PROTOBUF_FIELD_OFFSET(SubRequest, _impl_.minuend_)>(
          reinterpret_cast<char*>(&_impl_.minuend_),
          reinterpret_cast<char*>(&other->_impl_.minuend_));
}

::google::protobuf::Metadata SubRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SubResponse::_Internal {
 public:
};

SubResponse::SubResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:calculator.SubResponse)
}
SubResponse::SubResponse(
    ::google::protobuf::Arena* arena, const SubResponse& from)
    : SubResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SubResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SubResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.difference_ = {};
}
SubResponse::~SubResponse() {
  // @@protoc_insertion_point(destructor:calculator.SubResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SubResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
SubResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(SubResponse, _impl_._cached_size_),
              false,
          },
          &SubResponse::MergeImpl,
          &SubResponse::kDescriptorMethods,
          &descriptor_table_calculator_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> SubResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SubResponse_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::calculator::SubResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 difference = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(SubResponse, _impl_.difference_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SubResponse, _impl_.difference_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 difference = 1;
    {PROTOBUF_FIELD_OFFSET(SubResponse, _impl_.difference_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void SubResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:calculator.SubResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.difference_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* SubResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:calculator.SubResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 difference = 1;
  if (this->_internal_difference() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_difference(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calculator.SubResponse)
  return target;
}

::size_t SubResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:calculator.SubResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 difference = 1;
  if (this->_internal_difference() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_difference());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void SubResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SubResponse*>(&to_msg);
  auto& from = static_cast<const SubResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calculator.SubResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_difference() != 0) {
    _this->_impl_.difference_ = from._impl_.difference_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SubResponse::CopyFrom(const SubResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calculator.SubResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SubResponse::InternalSwap(SubResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.difference_, other->_impl_.difference_);
}

::google::protobuf::Metadata SubResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MulRequest::_Internal {
 public:
};

MulRequest::MulRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:calculator.MulRequest)
}
MulRequest::MulRequest(
    ::google::protobuf::Arena* arena, const MulRequest& from)
    : MulRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE MulRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MulRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, multiplicand_),
           0,
           offsetof(Impl_, multiplier_) -
               offsetof(Impl_, multiplicand_) +
               sizeof(Impl_::multiplier_));
}
MulRequest::~MulRequest() {
  // @@protoc_insertion_point(destructor:calculator.MulRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MulRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
MulRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(MulRequest, _impl_._cached_size_),
              false,
          },
          &MulRequest::MergeImpl,
          &MulRequest::kDescriptorMethods,
          &descriptor_table_calculator_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> MulRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MulRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::calculator::MulRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 multiplier = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MulRequest, _impl_.multiplier_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MulRequest, _impl_.multiplier_)}},
    // int32 multiplicand = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MulRequest, _impl_.multiplicand_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MulRequest, _impl_.multiplicand_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 multiplicand = 1;
    {PROTOBUF_FIELD_OFFSET(MulRequest, _impl_.multiplicand_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 multiplier = 2;
    {PROTOBUF_FIELD_OFFSET(MulRequest, _impl_.multiplier_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void MulRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:calculator.MulRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.multiplicand_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.multiplier_) -
      reinterpret_cast<char*>(&_impl_.multiplicand_)) + sizeof(_impl_.multiplier_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* MulRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:calculator.MulRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 multiplicand = 1;
  if (this->_internal_multiplicand() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_multiplicand(), target);
  }

  // int32 multiplier = 2;
  if (this->_internal_multiplier() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_multiplier(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calculator.MulRequest)
  return target;
}

::size_t MulRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:calculator.MulRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // int32 multiplicand = 1;
  if (this->_internal_multiplicand() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_multiplicand());
  }

  // int32 multiplier = 2;
  if (this->_internal_multiplier() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_multiplier());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void MulRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MulRequest*>(&to_msg);
  auto& from = static_cast<const MulRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calculator.MulRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_multiplicand() != 0) {
    _this->_impl_.multiplicand_ = from._impl_.multiplicand_;
  }
  if (from._internal_multiplier() != 0) {
    _this->_impl_.multiplier_ = from._impl_.multiplier_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MulRequest::CopyFrom(const MulRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calculator.MulRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MulRequest::InternalSwap(MulRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MulRequest, _impl_.multiplier_)
      + sizeof(MulRequest::_impl_.multiplier_)
      - PROTOBUF_FIELD_OFFSET(MulRequest, _impl_.multiplicand_)>(
          reinterpret_cast<char*>(&_impl_.multiplicand_),
          reinterpret_cast<char*>(&other->_impl_.multiplicand_));
}

::google::protobuf::Metadata MulRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class MulResponse::_Internal {
 public:
};

MulResponse::MulResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:calculator.MulResponse)
}
MulResponse::MulResponse(
    ::google::protobuf::Arena* arena, const MulResponse& from)
    : MulResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE MulResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void MulResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.product_ = {};
}
MulResponse::~MulResponse() {
  // @@protoc_insertion_point(destructor:calculator.MulResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MulResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
MulResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(MulResponse, _impl_._cached_size_),
              false,
          },
          &MulResponse::MergeImpl,
          &MulResponse::kDescriptorMethods,
          &descriptor_table_calculator_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> MulResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MulResponse_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::calculator::MulResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 product = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MulResponse, _impl_.product_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(MulResponse, _impl_.product_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 product = 1;
    {PROTOBUF_FIELD_OFFSET(MulResponse, _impl_.product_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void MulResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:calculator.MulResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.product_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* MulResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:calculator.MulResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 product = 1;
  if (this->_internal_product() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_product(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calculator.MulResponse)
  return target;
}

::size_t MulResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:calculator.MulResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 product = 1;
  if (this->_internal_product() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_product());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void MulResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<MulResponse*>(&to_msg);
  auto& from = static_cast<const MulResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calculator.MulResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_product() != 0) {
    _this->_impl_.product_ = from._impl_.product_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MulResponse::CopyFrom(const MulResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calculator.MulResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void MulResponse::InternalSwap(MulResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.product_, other->_impl_.product_);
}

::google::protobuf::Metadata MulResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DivRequest::_Internal {
 public:
};

DivRequest::DivRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:calculator.DivRequest)
}
DivRequest::DivRequest(
    ::google::protobuf::Arena* arena, const DivRequest& from)
    : DivRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE DivRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void DivRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, dividend_),
           0,
           offsetof(Impl_, divisor_) -
               offsetof(Impl_, dividend_) +
               sizeof(Impl_::divisor_));
}
DivRequest::~DivRequest() {
  // @@protoc_insertion_point(destructor:calculator.DivRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DivRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
DivRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(DivRequest, _impl_._cached_size_),
              false,
          },
          &DivRequest::MergeImpl,
          &DivRequest::kDescriptorMethods,
          &descriptor_table_calculator_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> DivRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DivRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::calculator::DivRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 divisor = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DivRequest, _impl_.divisor_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(DivRequest, _impl_.divisor_)}},
    // int32 dividend = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(DivRequest, _impl_.dividend_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(DivRequest, _impl_.dividend_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 dividend = 1;
    {PROTOBUF_FIELD_OFFSET(DivRequest, _impl_.dividend_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 divisor = 2;
    {PROTOBUF_FIELD_OFFSET(DivRequest, _impl_.divisor_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void DivRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:calculator.DivRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.dividend_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.divisor_) -
      reinterpret_cast<char*>(&_impl_.dividend_)) + sizeof(_impl_.divisor_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* DivRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:calculator.DivRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 dividend = 1;
  if (this->_internal_dividend() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_dividend(), target);
  }

  // int32 divisor = 2;
  if (this->_internal_divisor() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_divisor(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calculator.DivRequest)
  return target;
}

::size_t DivRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:calculator.DivRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // int32 dividend = 1;
  if (this->_internal_dividend() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_dividend());
  }

  // int32 divisor = 2;
  if (this->_internal_divisor() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_divisor());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void DivRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DivRequest*>(&to_msg);
  auto& from = static_cast<const DivRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calculator.DivRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_dividend() != 0) {
    _this->_impl_.dividend_ = from._impl_.dividend_;
  }
  if (from._internal_divisor() != 0) {
    _this->_impl_.divisor_ = from._impl_.divisor_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DivRequest::CopyFrom(const DivRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calculator.DivRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DivRequest::InternalSwap(DivRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(DivRequest, _impl_.divisor_)
      + sizeof(DivRequest::_impl_.divisor_)
      - PROTOBUF_FIELD_OFFSET(DivRequest, _impl_.dividend_)>(
          reinterpret_cast<char*>(&_impl_.dividend_),
          reinterpret_cast<char*>(&other->_impl_.dividend_));
}

::google::protobuf::Metadata DivRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class DivResponse::_Internal {
 public:
};

DivResponse::DivResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:calculator.DivResponse)
}
DivResponse::DivResponse(
    ::google::protobuf::Arena* arena, const DivResponse& from)
    : DivResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE DivResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void DivResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.quotient_ = {};
}
DivResponse::~DivResponse() {
  // @@protoc_insertion_point(destructor:calculator.DivResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void DivResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
DivResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(DivResponse, _impl_._cached_size_),
              false,
          },
          &DivResponse::MergeImpl,
          &DivResponse::kDescriptorMethods,
          &descriptor_table_calculator_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> DivResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_DivResponse_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::calculator::DivResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 quotient = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(DivResponse, _impl_.quotient_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(DivResponse, _impl_.quotient_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 quotient = 1;
    {PROTOBUF_FIELD_OFFSET(DivResponse, _impl_.quotient_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void DivResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:calculator.DivResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.quotient_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* DivResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:calculator.DivResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 quotient = 1;
  if (this->_internal_quotient() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_quotient(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calculator.DivResponse)
  return target;
}

::size_t DivResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:calculator.DivResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 quotient = 1;
  if (this->_internal_quotient() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_quotient());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void DivResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<DivResponse*>(&to_msg);
  auto& from = static_cast<const DivResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calculator.DivResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_quotient() != 0) {
    _this->_impl_.quotient_ = from._impl_.quotient_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void DivResponse::CopyFrom(const DivResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calculator.DivResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void DivResponse::InternalSwap(DivResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.quotient_, other->_impl_.quotient_);
}

::google::protobuf::Metadata DivResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ModRequest::_Internal {
 public:
};

ModRequest::ModRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:calculator.ModRequest)
}
ModRequest::ModRequest(
    ::google::protobuf::Arena* arena, const ModRequest& from)
    : ModRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ModRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ModRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, dividend_),
           0,
           offsetof(Impl_, divisor_) -
               offsetof(Impl_, dividend_) +
               sizeof(Impl_::divisor_));
}
ModRequest::~ModRequest() {
  // @@protoc_insertion_point(destructor:calculator.ModRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ModRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ModRequest::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(ModRequest, _impl_._cached_size_),
              false,
          },
          &ModRequest::MergeImpl,
          &ModRequest::kDescriptorMethods,
          &descriptor_table_calculator_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> ModRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ModRequest_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::calculator::ModRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int32 divisor = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ModRequest, _impl_.divisor_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ModRequest, _impl_.divisor_)}},
    // int32 dividend = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ModRequest, _impl_.dividend_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ModRequest, _impl_.dividend_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 dividend = 1;
    {PROTOBUF_FIELD_OFFSET(ModRequest, _impl_.dividend_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // int32 divisor = 2;
    {PROTOBUF_FIELD_OFFSET(ModRequest, _impl_.divisor_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ModRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:calculator.ModRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.dividend_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.divisor_) -
      reinterpret_cast<char*>(&_impl_.dividend_)) + sizeof(_impl_.divisor_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ModRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:calculator.ModRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int32 dividend = 1;
  if (this->_internal_dividend() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<1>(
            stream, this->_internal_dividend(), target);
  }

  // int32 divisor = 2;
  if (this->_internal_divisor() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_divisor(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calculator.ModRequest)
  return target;
}

::size_t ModRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:calculator.ModRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // int32 dividend = 1;
  if (this->_internal_dividend() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_dividend());
  }

  // int32 divisor = 2;
  if (this->_internal_divisor() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_divisor());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ModRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ModRequest*>(&to_msg);
  auto& from = static_cast<const ModRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calculator.ModRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_dividend() != 0) {
    _this->_impl_.dividend_ = from._impl_.dividend_;
  }
  if (from._internal_divisor() != 0) {
    _this->_impl_.divisor_ = from._impl_.divisor_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ModRequest::CopyFrom(const ModRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calculator.ModRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ModRequest::InternalSwap(ModRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ModRequest, _impl_.divisor_)
      + sizeof(ModRequest::_impl_.divisor_)
      - PROTOBUF_FIELD_OFFSET(ModRequest, _impl_.dividend_)>(
          reinterpret_cast<char*>(&_impl_.dividend_),
          reinterpret_cast<char*>(&other->_impl_.dividend_));
}

::google::protobuf::Metadata ModRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ModResponse::_Internal {
 public:
};

ModResponse::ModResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:calculator.ModResponse)
}
ModResponse::ModResponse(
    ::google::protobuf::Arena* arena, const ModResponse& from)
    : ModResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ModResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ModResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.result_ = {};
}
ModResponse::~ModResponse() {
  // @@protoc_insertion_point(destructor:calculator.ModResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ModResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
ModResponse::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(ModResponse, _impl_._cached_size_),
              false,
          },
          &ModResponse::MergeImpl,
          &ModResponse::kDescriptorMethods,
          &descriptor_table_calculator_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ModResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ModResponse_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::calculator::ModResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // int64 result = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ModResponse, _impl_.result_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(ModResponse, _impl_.result_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 result = 1;
    {PROTOBUF_FIELD_OFFSET(ModResponse, _impl_.result_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void ModResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:calculator.ModResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.result_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* ModResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:calculator.ModResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 result = 1;
  if (this->_internal_result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this->_internal_result(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:calculator.ModResponse)
  return target;
}

::size_t ModResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:calculator.ModResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 result = 1;
  if (this->_internal_result() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_result());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void ModResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ModResponse*>(&to_msg);
  auto& from = static_cast<const ModResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:calculator.ModResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_result() != 0) {
    _this->_impl_.result_ = from._impl_.result_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ModResponse::CopyFrom(const ModResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:calculator.ModResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ModResponse::InternalSwap(ModResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.result_, other->_impl_.result_);
}

::google::protobuf::Metadata ModResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace calculator
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_calculator_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
